name = "TestDoc"
uuid = "bde46a4e-9d8f-4e92-a122-2fcf0e58ed0a"
authors = ["KeishiS <sando.keishi.sp@alumni.tsukuba.ac.jp> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
